name: uas_project
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  audioplayers: ^5.2.1
  sensors_plus: ^5.0.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/car.jpg
    - assets/images/road.png
    - assets/audio/benar.mp3
    - assets/audio/clik.mp3
    - assets/audio/hancur.mp3
    - assets/audio/meledak.mp3
    - assets/audio/menabrak.mp3
    - assets/audio/music_bg.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"